// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPIEpYAB-p2CfnLsN9ZCSvktbr1fY9Zos',
    appId: '1:872044410878:web:0e17d06676d973a2ac72af',
    messagingSenderId: '872044410878',
    projectId: 'daily-expanses-2b007',
    authDomain: 'daily-expanses-2b007.firebaseapp.com',
    storageBucket: 'daily-expanses-2b007.firebasestorage.app',
    measurementId: 'G-8TH2R58LGP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwvZwvA3QsPxrLmhI9YqntHyyeQ3dlzzo',
    appId: '1:872044410878:android:321a21dac3051f4cac72af',
    messagingSenderId: '872044410878',
    projectId: 'daily-expanses-2b007',
    storageBucket: 'daily-expanses-2b007.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPIEpYAB-p2CfnLsN9ZCSvktbr1fY9Zos',
    appId: '1:872044410878:web:d7616b17c0e33fc9ac72af',
    messagingSenderId: '872044410878',
    projectId: 'daily-expanses-2b007',
    authDomain: 'daily-expanses-2b007.firebaseapp.com',
    storageBucket: 'daily-expanses-2b007.firebasestorage.app',
    measurementId: 'G-TFW56BZZ95',
  );
}
